### ISSUE TITLE
java.io.InvalidClassException: no valid constructor

### ISSUE THREAD

**Issue by Hebaallahibrahim** [SANSA-Stack/SANSA-ML#3] opened 2018-03-23 10:28 UTC
I have java.io.InvalidClassException: no valid constructor. I read about this exception I found that when trying to deserialize an object of serialized class the no_arg constructor is fired and if this constructor is not existed this exception throws. And I already have this no-arg constructor in my code but still, have this exception.

**Comment by patrickwestphal** [comment] 2018-04-05 12:36
Hi Heba,
can you please give some pointers where this error occurs and for which class?

**Comment by Hebaallahibrahim** [comment] 2018-04-05 12:40
Hi Patrick,
I have this error in KB class, I push the code on GitHub with _https://github.com/Hebaallahibrahim/TDTree.git_ you can clone it and put in SANSA-ML layer under classification in order to execute it

**Comment by patrickwestphal** [comment] 2018-04-05 13:39
Sorry, but I cannot reproduce this error.
First, please provide something like a Maven project, s.t. one doesn't have to add all dependencies manually. Then, even after adding all the dependencies I get compile errors. So, unfortunately I cannot check what's the problem here.

**Comment by Hebaallahibrahim** [comment] 2018-05-26 13:06
Hi Patrick, I create a new branch named develop-TDT in SANSA-ML and push the code to it

**Comment by patrickwestphal** [comment] 2018-06-14 13:12
First of all, there was a bug in the SANSA OWL layer which is fixed in the latest 0.3.1-SNAPSHOT build.
I think your problems stems from what you're doing e.g. in [this method](https://github.com/SANSA-Stack/SANSA-ML/blob/develp-TDT/sansa-ml-spark/src/main/scala/net/sansa_stack/ml/spark/classification/KB.scala#L158-L221). You're iterating through an RDD, calling e.g. the reasoner inside the loop. Since everything that is touched inside such iterations needs to be serialized and sent to the the respective executors, this also applies to the HermiT reasoner object, and everything 'inside' it. I understand that the usage of HermiT is just a 'quick hack' and not the final solution but I don't think it will work that way. I wrote a very lightweight alternative to the `KB` class for testing which just works on the axiom level, so without reasoning, but I cannot tell yet whether it works since the code already runs for ages on these ~ 300 axioms and I'm not even at the stage where the training starts. But I can nonetheless add this class if you want.

**Closed as completed** 2018-07-27 08:53 UTC
